; PlatformIO Project Configuration File

[env:airm2m_core_esp32c3]
platform = espressif32
board = airm2m_core_esp32c3
framework = arduino
monitor_speed = 115200
lib_deps =
    olikraus/U8g2@^2.34.22
    madhephaestus/ESP32Servo
